# Generated by Django 3.0.8 on 2020-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200725_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic1.png', null=True, upload_to='profile_images'),
        ),
    ]
