# Generated by Django 3.0.8 on 2020-08-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200726_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['date_created']},
        ),
    ]
