# Generated by Django 3.0.8 on 2020-08-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200809_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_created']},
        ),
    ]
